Add dokerfile and update github workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,6 +34,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: List files in repository
+        run: ls -la
+
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
@@ -42,15 +45,15 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Run lint (optional, comment out if not used)
-        run: |
-          if npm run lint; then
-            echo "Lint passed"
-          else
-            echo "Lint failed"
-            exit 1
-          fi
-        continue-on-error: true
+      # - name: Run lint (optional, comment out if not used)
+      #   run: |
+      #     if npm run lint; then
+      #       echo "Lint passed"
+      #     else
+      #       echo "Lint failed"
+      #       exit 1
+      #     fi
+      #   continue-on-error: true
 
       - name: Run tests (skipped if no tests are defined)
         run: |
@@ -74,6 +77,6 @@ jobs:
 
       - name: Build & Push Docker Image
         run: |
-          docker build -t quicktask-api .
+          docker build -t quicktask-api -f Dockerfile .
           docker tag quicktask-api ${{ secrets.DOCKER_HUB_USERNAME }}/quicktask-api:latest
           docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quicktask-api:latest
